import type { Product, Category, Testimonial, GalleryImage, SiteSettings, DietaryTag } from '@/lib/types'

export const fallbackCategories: Category[] = [
  { id: '1', name: 'Cakes', slug: 'cakes', order: 1 },
  { id: '2', name: 'Eggless Pastries', slug: 'eggless-pastries', order: 2 },
  { id: '3', name: 'Pizza', slug: 'pizza', order: 3 },
  { id: '4', name: 'Patties', slug: 'patties', order: 4 },
  { id: '5', name: 'Maggi', slug: 'maggi', order: 5 },
  { id: '6', name: 'Hot Beverages', slug: 'hot-beverages', order: 6 },
]

export const fallbackProducts: Product[] = [
  {
    id: '1',
    name: 'Vanilla Cake',
    slug: 'vanilla-cake',
    category: fallbackCategories[0],
    price: 250,
    priceLabel: '₹250 / ₹500',
    description: 'Eggless vanilla cake. Half kg ₹250 | 1 kg ₹500.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '2',
    name: 'Strawberry Cake',
    slug: 'strawberry-cake',
    category: fallbackCategories[0],
    price: 250,
    priceLabel: '₹250 / ₹500',
    description: 'Eggless strawberry cake. Half kg ₹250 | 1 kg ₹500.',
    images: ['/images/cakes/red-velvet-cake.jpg'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '3',
    name: 'Pineapple Cake',
    slug: 'pineapple-cake',
    category: fallbackCategories[0],
    price: 250,
    priceLabel: '₹250 / ₹500',
    description: 'Eggless pineapple cake. Half kg ₹250 | 1 kg ₹500.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '4',
    name: 'Butterscotch Cake',
    slug: 'butterscotch-cake',
    category: fallbackCategories[0],
    price: 250,
    priceLabel: '₹250 / ₹500',
    description: 'Eggless butterscotch cake. Half kg ₹250 | 1 kg ₹500.',
    images: ['/images/cakes/custom-tiered-cake.jpg'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '5',
    name: 'Blueberry Cake',
    slug: 'blueberry-cake',
    category: fallbackCategories[0],
    price: 260,
    priceLabel: '₹260 / ₹520',
    description: 'Eggless blueberry cake. Half kg ₹260 | 1 kg ₹520.',
    images: ['/images/cakes/birthday-theme-cake.jpg'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '6',
    name: 'Black Currant Cake',
    slug: 'black-currant-cake',
    category: fallbackCategories[0],
    price: 260,
    priceLabel: '₹260 / ₹550',
    description: 'Eggless black currant cake. Half kg ₹260 | 1 kg ₹550.',
    images: ['/images/cakes/doll-butterfly-cake.jpg'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: true,
    available: true,
  },
  {
    id: '7',
    name: 'Black Forest Cake',
    slug: 'black-forest-cake',
    category: fallbackCategories[0],
    price: 280,
    priceLabel: '₹280 / ₹560',
    description: 'Eggless black forest cake. Half kg ₹280 | 1 kg ₹560.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '8',
    name: 'White Forest Cake',
    slug: 'white-forest-cake',
    category: fallbackCategories[0],
    price: 280,
    priceLabel: '₹280 / ₹560',
    description: 'Eggless white forest cake. Half kg ₹280 | 1 kg ₹560.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '9',
    name: 'Chocolate Cake',
    slug: 'chocolate-cake',
    category: fallbackCategories[0],
    price: 300,
    priceLabel: '₹300 / ₹600',
    description: 'Eggless chocolate cake. Half kg ₹300 | 1 kg ₹600.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '10',
    name: 'Chocolate Truffle Cake',
    slug: 'chocolate-truffle-cake',
    category: fallbackCategories[0],
    price: 400,
    priceLabel: '₹400 / ₹800',
    description: 'Eggless chocolate truffle cake. Half kg ₹400 | 1 kg ₹800.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '11',
    name: 'Choco Chips Cake',
    slug: 'choco-chips-cake',
    category: fallbackCategories[0],
    price: 350,
    priceLabel: '₹350 / ₹700',
    description: 'Eggless choco chips cake. Half kg ₹350 | 1 kg ₹700.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '12',
    name: 'Oreo Cake',
    slug: 'oreo-cake',
    category: fallbackCategories[0],
    price: 320,
    priceLabel: '₹320 / ₹640',
    description: 'Eggless Oreo cake. Half kg ₹320 | 1 kg ₹640.',
    images: ['/images/category-cakes.png'],
    dietaryTags: ['vegetarian', 'eggless'],
    featured: false,
    available: true,
  },
  {
    id: '13', name: 'Fresh Fruit Cake', slug: 'fresh-fruit-cake', category: fallbackCategories[0], price: 350, priceLabel: '₹350 / ₹700',
    description: 'Eggless fresh fruit cake. Half kg ₹350 | 1 kg ₹700.', images: ['/images/category-cakes.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '14', name: 'Red Velvet Cake', slug: 'red-velvet-cake', category: fallbackCategories[0], price: 500, priceLabel: '₹500 / ₹1,000',
    description: 'Eggless red velvet cake. Half kg ₹500 | 1 kg ₹1,000.', images: ['/images/cakes/red-velvet-cake.jpg'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '15', name: 'Ras Malai Cake', slug: 'ras-malai-cake', category: fallbackCategories[0], price: 500, priceLabel: '₹500 / ₹1,000',
    description: 'Eggless ras malai cake. Half kg ₹500 | 1 kg ₹1,000.', images: ['/images/category-cakes.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '16', name: 'Doll Cake', slug: 'doll-cake', category: fallbackCategories[0], price: 200, priceLabel: '₹200 extra',
    description: 'Special cake extra charge for a doll cake design.', images: ['/images/cakes/doll-butterfly-cake.jpg'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '17', name: 'Photo Cake', slug: 'photo-cake', category: fallbackCategories[0], price: 300, priceLabel: '₹300 extra',
    description: 'Special cake extra charge for a photo cake design.', images: ['/images/cakes/birthday-theme-cake.jpg'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '18', name: 'Chocolate Choco Chips Pastry', slug: 'chocolate-choco-chips-pastry', category: fallbackCategories[1], price: 40, priceLabel: '₹40 / pc',
    description: 'Eggless pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: true, available: true,
  },
  {
    id: '19', name: 'Chocolate Pastry', slug: 'chocolate-pastry', category: fallbackCategories[1], price: 35, priceLabel: '₹35 / pc',
    description: 'Eggless chocolate pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '20', name: 'Pineapple Pastry', slug: 'pineapple-pastry', category: fallbackCategories[1], price: 30, priceLabel: '₹30 / pc',
    description: 'Eggless pineapple pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '21', name: 'Strawberry Pastry', slug: 'strawberry-pastry', category: fallbackCategories[1], price: 30, priceLabel: '₹30 / pc',
    description: 'Eggless strawberry pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '22', name: 'Butterscotch Pastry', slug: 'butterscotch-pastry', category: fallbackCategories[1], price: 30, priceLabel: '₹30 / pc',
    description: 'Eggless butterscotch pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '23', name: 'Vanilla Pastry', slug: 'vanilla-pastry', category: fallbackCategories[1], price: 30, priceLabel: '₹30 / pc',
    description: 'Eggless vanilla pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '24', name: 'Blueberry Pastry', slug: 'blueberry-pastry', category: fallbackCategories[1], price: 30, priceLabel: '₹30 / pc',
    description: 'Eggless blueberry pastry, priced per piece.', images: ['/images/category-pastries.png'], dietaryTags: ['vegetarian', 'eggless'], featured: false, available: true,
  },
  {
    id: '25', name: 'Veg Cheese Pizza', slug: 'veg-cheese-pizza', category: fallbackCategories[2], price: 60, priceLabel: '₹60 / ₹120', description: 'Veg cheese pizza in two sizes.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: true, available: true,
  },
  {
    id: '26', name: 'Onion Capsicum Pizza', slug: 'onion-capsicum-pizza', category: fallbackCategories[2], price: 60, priceLabel: '₹60 / ₹120', description: 'Onion and capsicum pizza in two sizes.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '27', name: 'Special Cheese Burst Pizza', slug: 'special-cheese-burst-pizza', category: fallbackCategories[2], price: 80, priceLabel: '₹80 / ₹160', description: 'Special cheese burst pizza in two sizes.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '28', name: 'Veg Patties', slug: 'veg-patties', category: fallbackCategories[3], price: 20, priceLabel: '₹20', description: 'Fresh vegetarian patties.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: true, available: true,
  },
  {
    id: '29', name: 'Paneer Patties', slug: 'paneer-patties', category: fallbackCategories[3], price: 25, priceLabel: '₹25', description: 'Fresh paneer patties.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '30', name: 'Veg Maggi', slug: 'veg-maggi', category: fallbackCategories[4], price: 40, priceLabel: '₹40', description: 'Vegetable Maggi.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: true, available: true,
  },
  {
    id: '31', name: 'Cheese Maggi', slug: 'cheese-maggi', category: fallbackCategories[4], price: 60, priceLabel: '₹60', description: 'Cheese Maggi.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '32', name: 'Masala Special Maggi', slug: 'masala-special-maggi', category: fallbackCategories[4], price: 60, priceLabel: '₹60', description: 'Special masala Maggi.', images: ['/images/category-savouries.png'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '33', name: 'Hot Coffee', slug: 'hot-coffee', category: fallbackCategories[5], price: 10, priceLabel: '₹10 / ₹15', description: 'Hot coffee in two sizes.', images: ['/images/menu/beverages.svg'], dietaryTags: ['vegetarian'], featured: true, available: true,
  },
  {
    id: '34', name: 'Ginger Tea', slug: 'ginger-tea', category: fallbackCategories[5], price: 6, priceLabel: '₹6 / ₹12', description: 'Fresh ginger tea in two sizes.', images: ['/images/menu/beverages.svg'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
  {
    id: '35', name: 'Kulhad Chai', slug: 'kulhad-chai', category: fallbackCategories[5], price: 10, priceLabel: '₹10', description: 'Chai served in a kulhad.', images: ['/images/menu/beverages.svg'], dietaryTags: ['vegetarian'], featured: false, available: true,
  },
]

export const fallbackTestimonials: Testimonial[] = [
  {
    id: '1',
    authorName: 'Priya Sharma',
    quote: 'The sourdough here is the real deal — crusty, tangy, and keeps beautifully for days. My weekly Sunday ritual.',
    rating: 5,
  },
  {
    id: '2',
    authorName: 'Rajesh Kumar',
    quote: 'Ordered a custom birthday cake for my daughter — vanilla bean with fresh strawberries. She hasn\'t stopped talking about it. The team listened to every detail.',
    rating: 5,
  },
  {
    id: '3',
    authorName: 'Anita Desai',
    quote: 'Almond croissants are worth the drive. Frangipane is perfectly balanced, not cloying. Get there early — they sell out by 10.',
    rating: 5,
  },
  {
    id: '4',
    authorName: 'Vikram Patel',
    quote: 'Finally, a bakery that does eggless right. The fruit tart was light, the custard silky, no compromise on flavor. Thank you.',
    rating: 5,
  },
]

export const googleReviewLinks = [
  'https://goo.gl/maps/cZJywiZyxnD5oMQi6?g_st=awb',
  'https://goo.gl/maps/m9UJAvtAwGNocNeK6?g_st=awb',
  'https://goo.gl/maps/v5kU5wFRQdEKVjv36?g_st=awb',
  'https://goo.gl/maps/qJK1TLVaUAyL8PPF6?g_st=awb',
  'https://goo.gl/maps/gxxEpLvsMQRcLSEQ7?g_st=awb',
  'https://goo.gl/maps/q6SLXgXdYTX8PpUG6?g_st=awb',
  'https://goo.gl/maps/xq1P6uLEz1CaKmZx8?g_st=awb',
]

export const fallbackGalleryImages: GalleryImage[] = [
  {
    id: '1',
    image: '/images/category-breads.png',
    caption: 'Morning bake — sourdough scoring',
    altText: 'Baker scoring a sourdough loaf before it goes into the oven',
  },
  {
    id: '2',
    image: '/images/category-pastries.png',
    caption: 'Croissant lamination — 82% butter',
    altText: 'Layers of butter being folded into croissant dough',
  },
  {
    id: '3',
    image: '/images/category-cakes.png',
    caption: 'Fresh fruit tart assembly',
    altText: 'Pastry chef arranging seasonal fruit on a vanilla custard tart',
  },
  {
    id: '4',
    image: '/images/cakes/red-velvet-cake.jpg',
    caption: 'Chocolate ganache mirror glaze',
    altText: 'Dark chocolate mirror glaze being poured over a celebration cake',
  },
  {
    id: '5',
    image: '/images/gallery/shop-front-wide.jpg',
    caption: 'Display case — pastries & breads',
    altText: 'Bakery display case filled with croissants, breads, and pastries',
  },
  {
    id: '6',
    image: '/images/category-cookies.png',
    caption: 'Cookie cooling rack',
    altText: 'Rows of chocolate chip cookies cooling on wire racks',
  },
    {
      id: '7',
      image: '/images/cakes/custom-tiered-cake.jpg',
      caption: 'Custom tiered celebration cake',
      altText: 'White two-tier celebration cake decorated with red roses and gold details',
    },
    {
      id: '8',
      image: '/images/cakes/red-velvet-cake.jpg',
      caption: 'Red velvet celebration cake',
      altText: 'Red velvet cake with white chocolate decorations and red cake pieces',
    },
    {
      id: '9',
      image: '/images/cakes/doll-butterfly-cake.jpg',
      caption: 'Doll and butterfly theme cake',
      altText: 'Pink doll cake decorated with colourful butterflies and piped frosting',
    },
    {
      id: '10',
      image: '/images/cakes/whisky-bottle-cake.jpg',
      caption: 'Whisky bottle theme cake',
      altText: 'Chocolate celebration cake decorated with a whisky bottle design',
    },
    {
      id: '11',
      image: '/images/cakes/birthday-theme-cake.jpg',
      caption: 'Birthday theme cake',
      altText: 'Lavender two-tier birthday cake with a fairy and butterfly decorations',
    },
    {
      id: '12',
      image: '/images/gallery/shop-front-wide.jpg',
      caption: 'Our bakery in Chetganj, Varanasi',
      altText: 'Street view of the Shree Ram Bakers storefront in Chetganj, Varanasi',
    },
    {
      id: '13',
      image: '/images/gallery/shop-front-1.jpg',
      caption: 'The Shree Ram Bakers storefront',
      altText: 'Front view of the Shree Ram Bakers shop with its red signboard and display counter',
    },
    {
      id: '14',
      image: '/images/gallery/shop-front-2.jpg',
      caption: 'Fresh bakes and everyday favourites',
      altText: 'Shree Ram Bakers shop entrance and front display counter',
    },
]

export const fallbackSettings: SiteSettings = {
  bakeryName: 'Shree Ram Bakers',
  tagline: 'Handcrafted with patience. Served with warmth.',
  logo: '/images/logo-shree-ram.svg',
  hours: [
    { day: 'Monday', open: '09:00', close: '23:00' },
    { day: 'Tuesday', open: '09:00', close: '23:00' },
    { day: 'Wednesday', open: '09:00', close: '23:00' },
    { day: 'Thursday', open: '09:00', close: '23:00' },
    { day: 'Friday', open: '09:00', close: '23:00' },
    { day: 'Saturday', open: '09:00', close: '23:00' },
    { day: 'Sunday', open: '09:00', close: '23:00' },
  ],
  address: 'C12/75 Lahangpura, Chetganj, Varanasi-221001',
  phone: '6389368233 / 9140198122',
  mapUrl: 'https://maps.app.goo.gl/HWMhPyYhbiXZEiuRA',
  socialLinks: [
    { platform: 'instagram', url: 'https://www.instagram.com/shree_ram_bakers.1?stkn=NDNyMTVhNXUzZHFp' },
    { platform: 'facebook', url: 'https://www.facebook.com/profile.php?id=61577326994019' },
    { platform: 'whatsapp', url: 'https://wa.me/916389368233' },
  ],
  heroImage: '/images/hero-bakery.png',
}
